### ISSUE TITLE
Running Matlab in background with JupyterHub

### ISSUE THREAD

**Issue by omarabb315** [mathworks-ref-arch/matlab-integration-for-jupyter#11]
Currently I am using JupyterHub to organize students' access to our university server. When users run a matlab script, it only saves the results if the user continue to open the window, but when he close it the results are not saved. However by default every session in JupyterHub found to be idle for more than 10 minutes will be culled, so could it be that the JupyterHub server does not consider running a script in a session as an active one?

Additional Note: I am using a Docker Spawner to run images of matlab which are built by Providing MATLAB as a Volume or Bind Mount using the documentation [here](https://github.com/mathworks-ref-arch/matlab-integration-for-jupyter/blob/main/matlab/README-mounted.md)

**Comment by prabhakk-mw** [comment]
Answered in https://github.com/mathworks/jupyter-matlab-proxy/issues/82
