### ISSUE TITLE
License checkout from 27000@server_name failed.

### ISSUE THREAD

**Issue by Rstar1998** [mathworks-ref-arch/matlab-integration-for-jupyter#12]
Hello,
I am trying to run a Matlab container on JupyterHub by using a built of this dockerfile with license server name (https://github.com/mathworks-ref-arch/matlab-integration-for-jupyter/blob/main/matlab/Dockerfile). 

But when I use Matlab Jupyter notebooks and start matlab I get this error.

Error
```
License checkout from 27000@server_name  failed. For more details, see https://github.com/mathworks/matlab-proxy/blob/main/MATLAB-Licensing-Info.md.
```

Error logs: 

```
License checkout failed.
License Manager Error -114
This release requires a network license manager update and a new license file from the License Center.

Troubleshoot this issue by visiting:
https://www.mathworks.com/support/lme/114

```

Now I am using Matlab2024b version (default one) in Jupyter but the one we use locally is of version 2012b. How do i resolve this issue ?

**Comment by Rstar1998** [comment]
cc : @prabhakk-mw

**Comment by prabhakk-mw** [comment]
Hi @Rstar1998 

As the error message attempts to  suggest, the license file you have is not geared to license newer versions of MATLAB.

Kindly contact your license administrator to generate/update the license manager and the associated license files to support R2024b.

Contacting [MathWorks Technical Support ](https://supportcases.mathworks.com/mwsupport/s/casetypeselection?language=en_US&c__caseParameter=AccountandLicensing&s_tid=srlp_mwa) would be the recommended course of action.

Apologies for the delayed response, and thank you for tagging me.
