### ISSUE TITLE
Wrong association of a tag to the 2024a image

### ISSUE THREAD

**Issue by SimaoBolota-MetaCell** [mathworks-ref-arch/matlab-integration-for-jupyter#13]
In the following commit https://github.com/mathworks-ref-arch/matlab-integration-for-jupyter/commit/4fb3a7763c5e7d8908917b618d8a2e07effe672b#diff-55d7759981ffb5ece9db207fef5eb96802c1fb59ea0f801d7dccbf774dd77bd9L25  no r2024a was added to the _matlab_release_tag_ in _.github/workflows/matlab-byoi-dockerfile.ym_l but instead there are two tags for r2024b

This creates an error when trying to run Jupyter with MATLAB integration, inside a Docker container
 ![image](https://github.com/user-attachments/assets/fdfe7f22-bd5f-4166-be15-f0df1ecf607c)

**Comment by prabhakk-mw** [comment]
Thank you for reporting the issue @SimaoBolota-MetaCell !

**Comment by prabhakk-mw** [comment]
@SimaoBolota-MetaCell , This repository has just received a rather large update.

I'm reaching out to you based on the information in this issue, and the possible impact on your workflow.

**BLOT**: The `jupyter-byoi-matlab-notebook` is no longer receiving updates and will be deprecated shortly.

**Description**:
We noticed that the base layer we were depending on (ie:`jupyter/base-notebook`) was not receiving any updates from the `docker-stacks` repository and the base layers have moved to `quay.io/jupyter/base-notebook`.

While incorporating this change we have decided to simplify this repository to only contain a single Dockerfile to build all combinations.

Also, we found that it wasn't useful to publish the `jupyter-byoi-matlab-notebook` image as a pre-built image. 

Apart from the Dockerfile, this repository now publishes 2 prebuilt images and have been described [here](https://github.com/mathworks-ref-arch/matlab-integration-for-jupyter?tab=readme-ov-file#pre-built-images). 

Essentially, the repo will now publish `jupyter-matlab-notebook` and `jupyter-mounted-matlab-notebook` as prebuilt images.

Based on your specific needs, you could use one of these 2 prebuilt images, or choose to build from the Dockerfile directly.

If you need any assistance related to this, please do create another issue describing the assistance you seek.

Thank you for using the MATLAB Integration for Jupyter!
