### ISSUE TITLE
Matlab cannot open when I run container

### ISSUE THREAD

**Issue by Barry-Chen-yup** [mathworks-ref-arch/matlab-integration-for-jupyter#7]
ARG MATLAB_RELEASE=r2022a
ARG MATLAB_PRODUCT_LIST="MATLAB"

ARG MW_CONTEXT_TAGS=MATLAB_PROXY:JUPYTER:MPM:V1

FROM mltooling/ml-workspace-gpu:0.13.2 AS base_jupyter_image

FROM base_jupyter_image
ARG MW_CONTEXT_TAGS
ARG MATLAB_RELEASE
ARG MATLAB_PRODUCT_LIST

USER root
ENV DEBIAN_FRONTEND="noninteractive" TZ="Asia/Taipei"
ARG MATLAB_DEPS_REQUIREMENTS_FILE="https://raw.githubusercontent.com/mathworks-ref-arch/container-images/main/matlab-deps/${MATLAB_RELEASE}/ubuntu20.04/base-dependencies.txt"
ARG MATLAB_DEPS_REQUIREMENTS_FILE_NAME="matlab-deps-${MATLAB_RELEASE}-base-dependencies.txt"

RUN wget ${MATLAB_DEPS_REQUIREMENTS_FILE} -O ${MATLAB_DEPS_REQUIREMENTS_FILE_NAME} && \
    export DEBIAN_FRONTEND=noninteractive && apt-get update && \
    xargs -a ${MATLAB_DEPS_REQUIREMENTS_FILE_NAME} -r apt-get install --no-install-recommends -y \
    wget \
    unzip \
    ca-certificates \
    xvfb \
    && apt-get clean \
    && apt-get -y autoremove \
    && rm -rf /var/lib/apt/lists/*
RUN wget -q https://www.mathworks.com/mpm/glnxa64/mpm && \ 
    chmod +x mpm && \
    ./mpm install \
    --release=${MATLAB_RELEASE} \
    --destination=/opt/matlab \
    --products ${MATLAB_PRODUCT_LIST} && \
    rm -f mpm /tmp/mathworks_root.log && \
    ln -s /opt/matlab/bin/matlab /usr/local/bin/matlab
WORKDIR /packages
RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && apt-get clean && apt-get autoremove && \
    wget -q https://github.com/mathworks/build-glibc-bz-19329-patch/releases/download/ubuntu-focal/all-packages.tar.gz && \
    tar -x -f all-packages.tar.gz \
    --exclude glibc-*.deb \
    --exclude libc6-dbg*.deb && \
    apt-get install --yes --no-install-recommends --allow-downgrades ./*.deb && \
    rm -fr /packages
WORKDIR /

RUN export DEBIAN_FRONTEND=noninteractive && apt-get update \
    && apt-get install --no-install-recommends -y  python3-distutils \
    && apt-get clean \
    && apt-get -y autoremove \
    && rm -rf /var/lib/apt/lists/* \
    && cd /opt/matlab/extern/engines/python \
    && python setup.py install || true
USER $NB_USER
WORKDIR /workspace
RUN python -m pip install jupyter-matlab-proxy
RUN jupyter labextension install @jupyterlab/server-proxy
ENV JUPYTER_ENABLE_LAB="yes"
ENV MW_CONTEXT_TAGS=${MW_CONTEXT_TAGS}

------------------------------------------------------------
command line: docker build --build-arg MATLAB_PRODUCT_LIST="MATLAB Deep_Learning_Toolbox Parallel_Computing_Toolbox"
I can build docker.
But when I run container and opened matlab. The web responed 504.

**Comment by prabhakk-mw** [comment]
Hi @Barry-Chen-yup 
Could you please paste the output on your terminal window in which you started the container ? I'm looking for logs there which might explain the issue.

**Comment by prabhakk-mw** [comment]
Please note that all the Dockerfiles in this repository are being built and these built container images are being published onto GHCR.
You could try to see if these pre-built containers are working for you and work backwards to discover how your base image `mltooling/ml-workspace-gpu:0.13.2`  is different.

To pull from GHCR:
docker pull ghcr.io/mathworks-ref-arch/matlab-integration-for-jupyter/jupyter-matlab-notebook:r2022b

**Comment by prabhakk-mw** [comment]
@Barry-Chen-yup , please reopen this issue if you still need help with this along with the requested information.
Thank you!
