### ISSUE TITLE
R2022b with the dockerfile for ubuntu:22.04 crashes after some minutes idle

### ISSUE THREAD

**Issue by ingemarh** [mathworks-ref-arch/matlab-integration-for-jupyter#8]
Just start it up, and let it stay in idle.
After 5-6 minutes, it crashes, without further interactions.

**Comment by prabhakk-mw** [comment]
@ingemarh Is this still reproducible at your end with the latest version of the container:
```
docker pull ghcr.io/mathworks-ref-arch/matlab-integration-for-jupyter/jupyter-matlab-notebook-ubuntu-2204:r2022b
```

Could you please share any crash logs from MATLAB?

**Comment by prabhakk-mw** [comment]
@ingemarh, please feel free to re-open the issue with the requested information.
